delete unnecessary file

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -30,29 +30,29 @@ else
 	echo "✔ Linter and Stylelint did not find any errors 🐛"
 fi
 
-build_exit_code=1
-echo "build..."
-eval $BUILDER
-build_exit_code=$?
+# build_exit_code=1
+# echo "build..."
+# eval $BUILDER
+# build_exit_code=$?
 
-if [ $build_exit_code -ne 0 ]; then
-	echo "❌ Ooopps build failed, check your code pls"
-	exit 1
-else
-	echo "✔ Build Success! Nice JOB!"
-fi
+# if [ $build_exit_code -ne 0 ]; then
+# 	echo "❌ Ooopps build failed, check your code pls"
+# 	exit 1
+# else
+# 	echo "✔ Build Success! Nice JOB!"
+# fi
 
-server_build_exit_code=1
-echo "server build..."
-eval $SERVER_BUILDER
-server_build_exit_code=$?
+# server_build_exit_code=1
+# echo "server build..."
+# eval $SERVER_BUILDER
+# server_build_exit_code=$?
 
-if [ $server_build_exit_code -ne 0 ]; then
-	echo "❌ Ooopps server build failed, check your code pls"
-	exit 1
-else
-	echo "✔ Build Success! Nice JOB!"
-fi
+# if [ $server_build_exit_code -ne 0 ]; then
+# 	echo "❌ Ooopps server build failed, check your code pls"
+# 	exit 1
+# else
+# 	echo "✔ Build Success! Nice JOB!"
+# fi
 
 # tester_exit_code=1
 # echo "testing..."
